Rename accordion module
Reloadly/reloadly-ui pull request #23
Opened 2023-10-04 06:54 UTC by OsamaAtReloadly

2023-10-04 07:01 UTC, iSeremet-Reloadly commented
Hey @OsamaAtReloadly do you see anything wrong with this PR?

2023-10-04 07:18 UTC, SabreFoxx-Reloadly commented on src/lib/components/modal/reloadly-modal-container/reloadly-modal-container.component.html
I already made these changes. I think there's something wrong with the PR

2023-10-04 07:38 UTC, salimzakari-reloadly commented
You need to sync your branch with main @OsamaAtReloadly

2023-10-04 07:55 UTC, farouk-reloadly commented
The PR is supposed to be into `develop` not `main` 👀

2023-10-04 08:56 UTC, iSeremet-Reloadly requested changes
!

2023-10-04 13:37 UTC, OsamaAtReloadly reviewed
@iSeremet-Reloadly Sorry I resynced with develop and change the destination branch.

2023-10-04 13:47 UTC, iSeremet-Reloadly approved these changes

2023-10-04 15:00 UTC, farouk-reloadly commented
@OsamaAtReloadly  you have to also increase the package version otherwise the build won't be successful

2023-10-04 15:18 UTC, salimzakari-reloadly approved these changes

2023-10-05 07:06 UTC, iSeremet-Reloadly approved these changes

2023-10-05 08:44 UTC, OsamaAtReloadly commented
> @OsamaAtReloadly you have to also increase the package version otherwise the build won't be successful

Updated now.

2023-10-07 10:11 UTC, SabreFoxx-Reloadly approved these changes

2023-10-09 09:12 UTC, merged